name: PR Reviewer
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  review:
    name: Perform review
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: github.actor == 'vincejv'
        uses: Ana06/automatic-pull-request-review@v0.1.0
        with:
          repo-token: ${{ secrets.FPI_BOT_TOKEN }}
          event: APPROVE
          body: 'Your code change was auto approved 🥳'
          allow_duplicate: false